# Generated by Django 4.1.5 on 2023-01-10 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.DurationField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
